services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  web:
    build: .
    volumes:
      - ./my_personal_diary:/app/my_personal_diary
      - static_data:/app/my_personal_diary/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A my_personal_diary.celery worker -l info
    depends_on:
      - redis
      - db
    env_file: .env

  celery-beat:
    build: .
    command: celery -A my_personal_diary.celery beat -l info
    depends_on:
      - redis
      - db
    env_file: .env

volumes:
  postgres_data:
  static_data: